### PR TITLE
change: sync config of APISIX V3 version

### PR DESCRIPTION
**Pull request by tzssangglass**
In APISIX V3 version, there are some breaking changes in `config-default.yaml`, and this PR is changed synchronously to this repo.

The following are the PRs I have filtered in relation to breaking changes: 
https://github.com/apache/apisix/pull/7716
https://github.com/apache/apisix/pull/7717
https://github.com/apache/apisix/pull/7806
https://github.com/apache/apisix/pull/7860
https://github.com/apache/apisix/pull/7823
https://github.com/apache/apisix/pull/7901 (in review)

I am not familiar with the helm chart, please let me know if there is anything else that needs to be changed.

### CODE REVIEW

**Review by nic-6443 — APPROVED** [review]

**Comment by tokers** [comment]
I have a concern that once we synced the content of `config.yaml` to v3, how can we improve the `config.yaml` for APISIX `v2.x`? IMHO the content of `config.yaml` in the ConfigMap may still lose some content in comparison to the one in APISIX repo. We don't have a release branch to allow us to iterate released versions.

Also, v3 is brand new and it's not uncommon that in a long while a lot of users will still use APISIX v2. It's worth paying more attention on this, not just syncing the differences.

**Comment by moonming** [comment]
> 

can we add `version` when installing apisix?

**Comment by tzssangglass** [comment]
There should be two versions, corresponding to V2 and V3 of APISIX?

**Comment by tokers** [comment]
> There should be two versions, corresponding to V2 and V3 of APISIX?

Yes.

**Comment by tao12345666333** [comment]
> I have a concern that once we synced the content of `config.yaml` to v3, how can we improve the `config.yaml` for APISIX `v2.x`? IMHO the content of `config.yaml` in the ConfigMap may still lose some content in comparison to the one in APISIX repo. We don't have a release branch to allow us to iterate released versions.
> 
> Also, v3 is brand new and it's not uncommon that in a long while a lot of users will still use APISIX v2. It's worth paying more attention to this, not just syncing the differences.
> 
> cc @tao12345666333 @moonming

Maybe we can maintain a new branch dedicated to releasing v3 related Helm charts.
But this causes users to install v3 silently when installing the latest version.

I suggest that instead of maintaining a specific branch, we can directly add a configuration item to complete its compatibility.

**Comment by tokers** [comment]
> > I have a concern that once we synced the content of `config.yaml` to v3, how can we improve the `config.yaml` for APISIX `v2.x`? IMHO the content of `config.yaml` in the ConfigMap may still lose some content in comparison to the one in APISIX repo. We don't have a release branch to allow us to iterate released versions.
> 
> > 
> 
> > Also, v3 is brand new and it's not uncommon that in a long while a lot of users will still use APISIX v2. It's worth paying more attention to this, not just syncing the differences.
> 
> > 
> 
> > cc @tao12345666333 @moonming
> 
> 
> 
> Maybe we can maintain a new branch dedicated to releasing v3 related Helm charts.
> 
> But this causes users to install v3 silently when installing the latest version.
> 
> 
> 
> I suggest that instead of maintaining a specific branch, we can directly add a configuration item to complete its compatibility.

You mean, translating the configuration according to the apisix version?

**Comment by tao12345666333** [comment]
It can be like this:

```
# Add option for APISIX major version.

if apisix_major_version == 'v3'
    # using v3 configuration template    
else
     # using v2 configuration template
```

Or we can add some translate logic in Chart.
I think this way the user experience will be better, but this may also lead to some confusion for users.

Typically, users prefer the configuration item to be the same as the actual configuration used.

**Comment by tzssangglass** [comment]
any news?

**Comment by tao12345666333** [comment]
I tend to use the first way.
If we want to continue, we should first reach a consensus

**Comment by tzssangglass** [comment]
what are your options? cc @tokers @nic-6443 @moonming @gxthrj

**Comment by tokers** [comment]
The `apisix_major_version` can be detected from the APISXI image? We don't need to let our users do the choice.

**Comment by tao12345666333** [comment]
> The `apisix_major_version` can be detected from the APISXI image? We don't need to let our users do the choice.

In this case, it means that APISIX is required to complete the compatibility of related configurations?

**Comment by tzssangglass** [comment]
> The `apisix_major_version` can be detected from the APISXI image? We don't need to let our users do the choice.

here: https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L588

**Comment by tzssangglass** [comment]
> In this case, it means that APISIX is required to complete the compatibility of related configurations?

In fact APISIX is hardly compatible and some modifications are inherently breaking change.

**Comment by tokers** [comment]
> > The `apisix_major_version` can be detected from the APISXI image? We don't need to let our users do the choice.
> 
> here: https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L588

I mean, from the APISIX image tag, we can know the version. Then we can decide how to render the config.

**Comment by tzssangglass** [comment]
> I mean, from the APISIX image tag, we can know the version.

Use an image with a 3.0 version number after the 3.0 release?
ref: https://hub.docker.com/r/apache/apisix/tags

**Comment by tokers** [comment]
> > I mean, from the APISIX image tag, we can know the version.
> 
> Use an image with a 3.0 version number after the 3.0 release? ref: https://hub.docker.com/r/apache/apisix/tags

Yep.

**Comment by tao12345666333** [comment]
you can use `semverCompare` for this one https://helm.sh/docs/chart_template_guide/function_list/#semvercompare

and `if/else` flow control https://helm.sh/docs/chart_template_guide/control_structures/#ifelse

**Pull request closed without merging**
