### PR TITLE
feat: allow exposing admin api via ingress resource

### PR DESCRIPTION
**Pull request by ikatlinsky**
Add support for ingress resource for Apisix admin API, as per ticket https://github.com/apache/apisix-helm-chart/issues/441.

### CODE REVIEW

**Comment by ikatlinsky** [comment]
@tao12345666333 hi! can please someone look at the proposed changes and related improvement created?

thanks

**Review by tokers — APPROVED** [review]

**Comment by tao12345666333** [comment]
As simple as this is, I'd like to know your use case.

this is a very dangerous behavior

**Comment by ikatlinsky** [comment]
@tao12345666333 sure, use case is the following:

we are deploying apisix in the private network, which is not available for public usage and needs a convenient way to interact with admin API for automation purposes. We will need to use port-forward functionality which is definitely not the very production-ready solution.

hope that helps

**Comment by ikatlinsky** [comment]
@tao12345666333 fixed problem with wrong documentation style

**Comment by tao12345666333** [comment]
Got it.

If so, it really needs to be exposed.


But I need to remind you that this behavior is really dangerous,
Because the Admin API is verified by username and password, once it is cracked by violence, it will be very dangerous

**Review by tao12345666333 — APPROVED** [review]
LGTM

**Comment by KID-G** [comment]
> Add support for ingress resource for Apisix admin API, as per ticket #441.

Hi,
Thank you for your contribution to Apache APISIX!
To express our gratitude and encouragement for your contribution, the Apache APISIX community would like to present to you the APISIX Contributor Certificate! You can check the sample certificate and fill out the form below, and after verifying, we will send the certificate to you. You can then save it, print it out, or share it with your social networks!

**To obtain the certificate:**
Fill out this [Google form](https://forms.gle/DhPL96LnJwuaHjHU7)
Alternatively, you can visit the official APISIX GitHub page to fill out the form: [GitHub page](https://github.com/apache/apisix/blob/master/CONTRIBUTING.md)

If you are in Chinese Mainland, you can fill out [Tencent form](https://wj.qq.com/s2/11438041/7b07) in Chinese.

**Pull request merged**
