### PR TITLE
chore: release apisix v1.6.2 with dashboard v0.8.1, ingress v0.12.1

### PR DESCRIPTION
**Pull request by ikatlinsky**
Including the latest dashboard chart version 0.8.1 for apisix chart

### CODE REVIEW

**Comment by ikatlinsky** [comment]
@tao12345666333 @AlinsRan @Gallardot please, review

**Comment by ikatlinsky** [comment]
let's wait for https://github.com/apache/apisix-helm-chart/pull/619 to be merged

**Comment by ikatlinsky** [comment]
ready to be reviewed and merged
@tao12345666333 @AlinsRan @Gallardot

**Review by tao12345666333 — APPROVED** [review]
LGTM

**Review by Gallardot — APPROVED** [review]

**Pull request merged**
