### PR TITLE
add allow_admin rest support

### PR DESCRIPTION
**Pull request by riskgod**

### CODE REVIEW

**Comment by tokers** [comment]
@riskgod This step can be done to add a `set` option to append the `0.0.0.0`.

**Comment by riskgod** [comment]
> @riskgod This step can be done to add a `set` option to append the `0.0.0.0`.

Ok, my fault, Close this PR.

**Comment by riskgod** [comment]
> @riskgod This step can be done to add a `set` option to append the `0.0.0.0`.

hey would you mind give an example here? Thank you man

**Comment by riskgod** [comment]
> @riskgod This step can be done to add a `set` option to append the `0.0.0.0`.

hey would you mind give an example here? Thank you man

**Pull request closed without merging**
