### PR TITLE
update apisix-ingress-controller crd to support hmacAuth

### PR DESCRIPTION
**Pull request by Fatpa**
Support hmacAuth for helm chart.
Needs to upgrade to the latest apisix-ingress-controller version, but I don't know which one now, I don't modify the values.yaml.

Ref to [#1035](https://github.com/apache/apisix-ingress-controller/pull/1035)

### CODE REVIEW

**Comment by tao12345666333** [comment]
Sorry, we will not modify the CRD file until the new version (v1.5) of APISIX Ingress controller is released, because this change will not take effect in the current v1.4.1

**Comment by Fatpa** [comment]
So we should wait for the v1.5 of Apisix Ingress controller and continue this PR?

**Comment by tao12345666333** [comment]
Yep. when APISIX Ingress v1.5 released, we need update all CRDs and apisix-ingress-controller's image.

**Comment by tao12345666333** [comment]
Thanks #331 has been merged, this one has been included.

I think we can close this one

**Pull request closed without merging**
