### PR TITLE
fix: dashboard ingress and apisix gateway ingress

### PR DESCRIPTION
**Pull request by ntfs32**
fix dashboard ingress apiVersion when kubernetes version in v14 newline bug,

add apisix gateway ingress suppurt, just in default values.yaml, not any ingress defined.

### CODE REVIEW

**Review by tokers — APPROVED** [review]

**Comment by tokers** [comment]
@ntfs32 Thanks for your contribution, it looks good to me.

**Comment by Junnplus** [comment]
LGTM, @tokers we can merge this ?

**Review by Junnplus — APPROVED** [review]

**Comment by tokers** [comment]
@gxthrj please take a look when you have time.

**Review by gxthrj — APPROVED** [review]
LGTM

**Pull request merged**
