### PR TITLE
feat: Configures APISIX Control API related Resources

### PR DESCRIPTION
**Pull request by kworkbee**
Complemented for missing resources related to Control API.
https://apisix.apache.org/docs/apisix/control-api/

### CODE REVIEW

**Comment by kworkbee** [comment]
@Revolyssup @shreemaan-abhishek

**Comment by Revolyssup** [comment]
@kworkbee Can you please fix the failing CI?

**Comment by kworkbee** [comment]
> @kworkbee Can you please fix the failing CI?

Can you explain in detail where the problem occurs?

**Comment by Revolyssup** [comment]
@kworkbee Can you fix the merge conflicts? Dev branch just got merged with master so these conflicts came up.

**Comment by kworkbee** [comment]
> @kworkbee Can you fix the merge conflicts? Dev branch just got merged with master so these conflicts came up.

I think something was handled incorrectly in the rebase process. I'll open it up again.

**Pull request closed without merging**
