### PR TITLE
feat: allow to provide etcd creds from secrets

### PR DESCRIPTION
**Pull request by ikatlinsky**
Gives a way to provide user, password and root password for etcd from existing Kubernetes secrets, as per proposal https://github.com/apache/apisix-helm-chart/issues/554.

### CODE REVIEW

**Comment by ikatlinsky** [comment]
@tao12345666333 @tokers can i ask you to take a look at the proposed changes and share your ideas?

**Review by lingsamuel — APPROVED** [review]

**Comment by tao12345666333** [comment]
please resolve conflicts. thanks

**Comment by ikatlinsky** [comment]
@tao12345666333 you are welcome, conflicts resolved

**Comment by ikatlinsky** [comment]
@tao12345666333 @AlinsRan anything else is required to progress on these changes?

**Comment by tao12345666333** [comment]
Thank you for your contribution. As our e2e test case does not cover this scenario, may I ask if you have tested it?

**Comment by ikatlinsky** [comment]
sure, will do that

**Comment by ikatlinsky** [comment]
@tao12345666333 i do not see any e2e tests at all for helm charts. I am looking into the wrong place or should i bootstrap a first base line for tests?

**Comment by lingsamuel** [comment]
we have test in github actions 
https://github.com/apache/apisix-helm-chart/blob/master/.github/workflows/ci.yaml

**Comment by ikatlinsky** [comment]
@lingsamuel yes, but as i understand it is just a simple check to test if the chart with default settings can be deployed without errors to the Kubernetes cluster - kind in case of the test. Is there any way to provide a custom configuration with support of password protected etcd?

**Comment by lingsamuel** [comment]
Yes, right now there is only a simple default conf deployment test.
We want another simple conf deployment test with etcd password.

**Comment by ikatlinsky** [comment]
Ok, will look at what I can do here, thanks for the clarification

**Comment by ikatlinsky** [comment]
@tao12345666333 @lingsamuel @AlinsRan I added an additional test to cover cases when with create password-protected etcd and providing username and password from a secret.

Unfortunately, I had to update the chart itself to allow it to create custom secrets based on the provided config, possible there are better solutions for that.

**Review by lingsamuel — APPROVED** [review]
LGTM, thanks for your work and patience

**Comment by Sn0rt** [comment]
pls take a look @sn0rt

**Review by tao12345666333 — APPROVED** [review]

**Pull request merged**
