### PR TITLE
chore: bump etcd chart to 7.0.1

### PR DESCRIPTION
**Pull request by Gallardot**
fix https://github.com/apache/apisix-helm-chart/issues/229

### CODE REVIEW

**Comment by tokers** [comment]
@Gallardot Could you check out the CI failure problems? Thanks!

**Comment by tokers** [comment]
@Gallardot It's duplicated with #261 ?

**Comment by Gallardot** [comment]
> @Gallardot Could you check out the CI failure problems? Thanks!

```
...Unable to get an update from the "https://charts.apiseven.com/" chart repository:
	Get "https://charts.apiseven.com/index.yaml": dial tcp: lookup charts.apiseven.com on 127.0.0.53:53: read udp 127.0.0.1:39590->127.0.0.53:53: i/o timeout
```

@tokers 
It seems that there was a network abnormality in CI at that time. Could you help me try again? I'm not authorized to perform this operation






> @Gallardot It's duplicated with #261 ?

Yes. I didn't realize there was already a similar PR until I created this one.  But I think #261 has some problems, because some configurations of etcd have changed after the upgrade of etcd chart version.

**Comment by tokers** [comment]
> > @Gallardot Could you check out the CI failure problems? Thanks!
> 
> ```
> ...Unable to get an update from the "https://charts.apiseven.com/" chart repository:
> 	Get "https://charts.apiseven.com/index.yaml": dial tcp: lookup charts.apiseven.com on 127.0.0.53:53: read udp 127.0.0.1:39590->127.0.0.53:53: i/o timeout
> ```
> 
> @tokers It seems that there was a network abnormality in CI at that time. Could you help me try again? I'm not authorized to perform this operation
> 
> > @Gallardot It's duplicated with #261 ?
> 
> Yes. I didn't realize there was already a similar PR until I created this one. But I think #261 has some problems, because some configurations of etcd have changed after the upgrade of etcd chart version.

You can add comments on #261, since we already have such one, please close this PR, thanks!

**Pull request closed without merging**
