### PR TITLE
feat: upgrade ETCD to 6.13.5

### PR DESCRIPTION
**Pull request by leshalv**

### CODE REVIEW

**Comment by tao12345666333** [comment]
Thanks

**Comment by tokers** [comment]
One of the Helm Cart Lint checks failed, PTAL, thanks @leshalv .

**Comment by leshalv** [comment]
这个是什么原因呀？

**Comment by tao12345666333** [comment]
In the new version of etcd chart, the authentication part has been modified.  Please try to install and modify the default configuration

**Pull request closed without merging**
