### PR TITLE
fix: revert Topology Spread Constraints to apisix

### PR DESCRIPTION
**Pull request by jenciso**
This PR add topologySpreadContrainsts option for apisix deployment

It was introduced [here](https://github.com/apache/apisix-helm-chart/pull/581/files), but it was removed

### CODE REVIEW

**Comment by ikatlinsky** [comment]
> Hi @ikatlinsky. Sorry to interrupt you. Please, could you review this little PR and the [other](https://github.com/apache/apisix-helm-chart/pull/759) also. Thank you

hi! i think helm docs was not updated, which is the cause of failing build. There is a make file in the repo with job helm-docs to do that.

**Comment by jenciso** [comment]
> > Hi @ikatlinsky. Sorry to interrupt you. Please, could you review this little PR and the [other](https://github.com/apache/apisix-helm-chart/pull/759) also. Thank you
> 
> hi! i think helm docs was not updated, which is the cause of failing build. There is a make file in the repo with job helm-docs to do that.

Ok, I just added it

**Comment by ikatlinsky** [comment]
@AlinsRan, @Gallardot can you please take a look at this PR, thanks

**Review by Gallardot — APPROVED** [review]
LGTM, Thank you for your contribution!

**Review by AlinsRan — APPROVED** [review]

**Pull request merged**
