### PR TITLE
fix: enable stream_route mode when ingress enabled

### PR DESCRIPTION
**Pull request by tao12345666333**
Since the release of APISIX v2.12, we found that when using Helm chart to install both APISIX and Ingress controller, the Ingress controller does not work properly.

This is because the stream_route mode is disabled by default in APISIX, but it is required by the Ingress controller.

xref:
issue: https://github.com/apache/apisix-ingress-controller/issues/851#issuecomment-1026306420
https://github.com/apache/apisix-ingress-controller/issues/858

Another fix on the APISIX Ingress controller is tracked at https://github.com/apache/apisix-ingress-controller/issues/856

### CODE REVIEW

**Comment by tao12345666333** [comment]
This is a serious problem, we need an upgrade version to release it immediately.

**Comment by Gallardot** [comment]
Maybe we should update both Deployment and Service as well.

**Comment by Gallardot** [comment]
> Why? This is for compatibility with Ingress controller behavior only, not for APISIX users. If the user really needs to expose stream_route, then modify the corresponding configuration.

Okay, got it

**Review by lingsamuel — APPROVED** [review]

**Review by bzp2010 — APPROVED** [review]
LGTM

**Pull request merged**
