### PR TITLE
feat: support overriding ServiceMonitor name

### PR DESCRIPTION
**Pull request by haoxins**

### CODE REVIEW

**Review by tokers — APPROVED** [review]

**Review by tokers — CHANGES_REQUESTED** [review]
It seems that `servicemonitor` is OK and what does the consistent mean? To be consistent with which files?

**Comment by haoxins** [comment]
> It seems that `servicemonitor` is OK and what does the consistent mean? To be consistent with which files?

```
service-admin.yaml
service-gateway.yaml
```

with the pattern `service-` 😂

**Comment by haoxins** [comment]
@tokers updated :)

**Review by tokers — APPROVED** [review]
I changed the title to make it complies the changes. @haoxins

**Review by zaunist — APPROVED** [review]

**Review by gxthrj — APPROVED** [review]

**Pull request merged**
