### PR TITLE
add extraInitContainers

### PR DESCRIPTION
**Pull request by ohayak**
I added an optional parameter to configure extra initContainers

the purpose of this option is to give user an option to do more customization, in my case it was to patch config files in order to support Stand-alone mode. Stand-alone mode won't be easily deployable before v3.0.0 but for people using v2 it's tricky to make it work without extra customization.

### CODE REVIEW

**Comment by tao12345666333** [comment]
Can you add more detailed background to the description? Why do we need this? What problem can it solve? thanks

**Comment by ohayak** [comment]
> Can you add more detailed background to the description? Why do we need this? What problem can it solve? thanks

description updated

**Comment by tokers** [comment]
> I added an optional parameter to configure extra initContainers
> 
> 
> 
> the purpose of this option is to give user an option to do more customization, in my case it was to patch config files in order to support Stand-alone mode. Stand-alone mode won't be easily deployable before v3.0.0 but for people using v2 it's tricky to make it work without extra customization.

Interesting, I think the way is worthy to be written in the docs. Would you also update the docs to introduce the way you patch the config to support the standalone mode.

**Comment by tao12345666333** [comment]
> in my case it was to patch config files in order to support Stand-alone mode.

Could you update the documentation to add a specific description about it?

There is currently a similar document describing stand-alone mode
https://github.com/apache/apisix-helm-chart/pull/366

**Comment by g-javi** [comment]
This is also helpful when changing ownership of mounted volumes (e.g. hostpath) when the `file-logger` plugin is used.

**Review by g-javi — APPROVED** [review]
LGTM!

**Comment by g-javi** [comment]
@tao12345666333 @tokers any update on this?

**Review by lingsamuel — APPROVED** [review]

**Review by tokers — APPROVED** [review]

**Review by tao12345666333 — APPROVED** [review]

**Pull request merged**
